export const ADDCOURSE = 'ADDCOURSE'

export const ADDCOURSELIST = 'ADDCOURSELIST'

export const ADDSECTION = 'ADDSECTION'

export const ADDSECTIONLIST = 'ADDSECTIONLIST'

export const ADDCOURSEINFO = 'ADDCOURSEINFO'
